### ISSUE TITLE
Paid posts not working. 

### ISSUE THREAD

**Issue by MLWhiz** [ZhgChgLi/ZMediumToMarkdown#14]
Only extracting part of post: Example - https://thealgorithmicminds.com/how-to-use-huggingface-to-use-llama-2-on-your-custom-machine-35713a2964de

**Comment by zhgchgli0718** [comment]
Medium has changed its rules for accessing paid articles, requiring users to log in in order to view them.

As a result, backup tools are also unable to crawl or retrieve paid articles.

To expand the functionality and enable proper execution, it would be necessary to incorporate the ability to simulate a logged-in state on Medium.

**Comment by zhgchgli0718** [comment]
resolved
