### ISSUE TITLE
Error: OpenSSL & deprecated `set-output` + thank you!

### ISSUE THREAD

**Issue by rafapolo** [ZhgChgLi/ZMediumToMarkdown#4]
Two problems I run into,

1) Probably an image referenced with a wrong SSL support. This should be "rescued" in a block.
#Error: OpenSSL::SSL::SSLError SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (unable to get local issuer certificate)

```
/opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/ZMediumToMarkdown-2.0.12/lib/ZMediumFetcher.rb:256:in `block in downloadPost'
/opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/ZMediumToMarkdown-2.0.12/lib/ZMediumFetcher.rb:248:in `open'
```

2)  Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ 

Thank you for this tool!

I had my own crawler but having it as a Github Action is excellent!

**Comment by zhgchgli0718** [comment]
I'll check the problems later, thanks for your feedback :)

**Comment by rafapolo** [comment]
any chance to handle the broken SSLErrors?

**Comment by zhgchgli0718** [comment]
A1:
after I tried, the SSL Error `certificate verify failed` it's because your environment's timestamp is not correct.
you can open a URL like `https://pinkoi.com` and the browser will tell you that your clock is behind.
<img width="656" alt="image" src="https://user-images.githubusercontent.com/33706588/201250730-fe9fe036-6bef-4700-a3c7-a7528e13c712.png">

A2:
thanks for your information! but ZMediumToMarkdown doesn't use `set-output`,  I'll resend the message to [git-auto-commit-action](https://github.com/stefanzweifel/git-auto-commit-action)
